import {
  Activity,
  Baby,
  Box,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Car,
  CircleDot,
  Construction,
  Dog,
  Dumbbell,
  Eye,
  Flower2,
  Hammer,
  HardHat,
  Heart,
  Home,
  Leaf,
  Lightbulb,
  LucideIcon,
  Megaphone,
  Music,
  Scale,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Thermometer,
  Truck,
  Utensils,
  Wrench,
} from 'lucide-react';
import { IconType } from 'react-icons';
import { FaSprayCan, FaToolbox } from 'react-icons/fa';

interface Industry {
  icon: LucideIcon | IconType;
  name: string;
}

export const industries: Industry[] = [
  { icon: Megaphone, name: 'Marketing Agency' },
  { icon: Calendar, name: 'Event Planner' },
  { icon: Wrench, name: 'Garage Door Contractor' },
  { icon: HardHat, name: 'Contractor' },
  { icon: Stethoscope, name: 'Chiropractor' },
  { icon: Thermometer, name: 'HVAC Contractor' },
  { icon: Dog, name: 'Veterinarian' },
  { icon: CircleDot, name: 'Dentist' },
  { icon: Briefcase, name: 'Professional Services' },
  { icon: Hammer, name: 'Flooring Contractor' },
  { icon: Eye, name: 'Optometrist' },
  { icon: Building2, name: 'Franchise' },
  { icon: Lightbulb, name: 'Consultant' },
  { icon: Shield, name: 'Insurance' },
  { icon: FaToolbox, name: 'Plumbing Contractor' },
  { icon: Scissors, name: 'Salon / Barber Shop' },
  { icon: Scale, name: 'Attorney / Law Firm' },
  { icon: Utensils, name: 'Restaurant / Bar' },
  { icon: Home, name: 'Real Estate' },
  { icon: Box, name: 'Self Storage Center' },
  { icon: ShoppingBag, name: 'Retail Store' },
  { icon: Flower2, name: 'Landscaping' },
  { icon: Heart, name: 'Therapist' },
  { icon: Sparkles, name: 'Spa' },
  { icon: FaSprayCan, name: 'Cleaning Company' },
  { icon: Bug, name: 'Pest Control' },
  { icon: Activity, name: 'Doctor / Medical' },
  { icon: ShoppingCart, name: 'eCommerce Store' },
  { icon: Leaf, name: 'Lawn Care' },
  { icon: Dumbbell, name: 'Fitness / Trainer / Gym' },
  { icon: Baby, name: 'Child Care' },
  { icon: Music, name: 'Dance Studio' },
  { icon: Truck, name: 'Moving Company' },
  { icon: Car, name: 'Auto Repair' },
  { icon: Calculator, name: 'Accounting Firm / CPA' },
  { icon: Construction, name: 'Roofing' },
];
