import {
  Briefcase,
  Calendar,
  Wrench,
  Stethoscope,
  Building2,
  ClipboardList,
  Warehouse,
  Eye,
  LineChart,
  Scale,
  UtensilsCrossed,
  Home,
  Box,
  ShoppingBag,
  Palmtree,
  HeartPulse,
  Bed,
  SprayCan,
  Bug,
  Syringe,
  ShoppingCart,
  Scissors,
  Dumbbell,
  Baby,
  Car,
  Calculator,
  Construction,
  Building,
  Music,
  LucideIcon,
} from 'lucide-react';
import { IconType } from 'react-icons';

interface Business {
  name: string;
  icon: LucideIcon | IconType;
}

export const businesses: Business[] = [
  { name: 'Marketing Agency', icon: Briefcase },
  { name: 'Event Planner', icon: Calendar },
  { name: 'Contractor', icon: Wrench },
  { name: 'Chiropractor', icon: Stethoscope },
  { name: 'HVAC Contractor', icon: Building2 },
  { name: 'Dentist', icon: Building2 },
  {
    name: 'Professional Services',
    icon: ClipboardList,
  },
  { name: 'Flooring Contractor', icon: Warehouse },
  { name: 'Optometrist', icon: Eye },
  { name: 'Consultant', icon: LineChart },
  { name: 'Attorney / Law Firm', icon: Scale },
  { name: 'Restaurant / Bar', icon: UtensilsCrossed },
  { name: 'Real Estate', icon: Home },
  { name: 'Self Storage Center', icon: Box },
  { name: 'Retail Store', icon: ShoppingBag },
  { name: 'Landscaping', icon: Palmtree },
  { name: 'Therapist', icon: HeartPulse },
  { name: 'Spa', icon: Bed },
  { name: 'Cleaning Company', icon: SprayCan },
  { name: 'Pest Control', icon: Bug },
  { name: 'Doctor / Medical', icon: Syringe },
  { name: 'eCommerce Store', icon: ShoppingCart },
  { name: 'Salon / Barber Shop', icon: Scissors },
  { name: 'Fitness / Trainer / Gym', icon: Dumbbell },
  { name: 'Child Care', icon: Baby },
  { name: 'Auto Repair', icon: Car },
  { name: 'Accounting Firm / CPA', icon: Calculator },
  { name: 'Roofing', icon: Construction },
  { name: 'Hotels', icon: Building },
  { name: 'Dance Studio', icon: Music },
];
